accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    #path('', views.signup_view, name="account-main"),
    #path('<str:username>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    #path('signup/', views.signup_view, name="signup"),
    #path('staff_signup/', views.staffsignup_view, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    #path('update/', views.account_update, name="account_update")

]

prestaproyector/urls.py
from django.contrib import admin
from django.urls import path, include
from prestaproyector import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.solicitud, name="solicitud"),
    path('sol_proyector/', views.prefill_solicitud, name="prefill_solicitud"),
    path('enviar_solicitud/', views.solicitud_proyector, name="sol_proyector"),
    path('registrar_proyector/', views.registrar_proyector, name="add_proyector"),
    path('registrar_componente/', views.registrar_componente, name="add_componente"),
    path('registrar_solicitante/', views.registrar_solicitante, name="add_solicitante"),
    path('exportar_csvs_prestamos/', views.exportar_csv_prestamos, name="exportar_csv_prestamos"),
    path('exportar_csvs_solicitantes/', views.exportar_csv_solicitantes, name="exportar_csv_solicitantes"),
    #path('exportar_csvs_proyectores/', views.exportar_csv_proyectores, name="exportar_csvs_proyectores"),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('lista_prestamos/', views.lista_prestamos, name="lista_prestamos"),
    path('devolucion/<id>', views.devolucion, name="devolucion"),
    path('marcar_incidencia/<id>', views.marcar_incidencia, name="marcar_incidencia"),
    path('proyectores/', views.status_proyectores, name="proyectores"),
    path('proyector_status_update/<id>', views.proyector_status_update, name="proyector_status_update"),
    path('componente_status_update/<id>', views.componente_status_update, name="componente_status_update"),
    path('solicitantes/', views.solicitantes, name="solicitantes"),
    path('bloquear_solicitante/<id>', views.bloquear_solicitante, name="bloquear_solicitante")
]

prestaproyector/forms.py
from django.db import models
from django import forms
from django.utils.safestring import mark_safe
from .models import Prestamo, Proyector, Solicitante, Materia, Componente
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

class SolicitudProyector_Form(forms.ModelForm):
    required_css_class = 'required'
    componentes = forms.ModelMultipleChoiceField(queryset=Componente.objects.filter(disponible=True), widget=forms.CheckboxSelectMultiple, required=False)
    


    def clean_solicitante(self):
        solicitante = self.cleaned_data.get('solicitante')
        try:
            Solicitante.objects.get(matricula=solicitante)
        except Solicitante.DoesNotExist:
            msg = forms.ValidationError(mark_safe('Matricula no existente en el sistema. <strong>Verifique que lo haya ingresado correctamente</strong> o <a href="/prestaproyector/registrar_solicitante/">Registrese aquí</a>'))
            self.add_error('solicitante', msg)
            raise msg
        return solicitante

    def clean_aula(self):
        aula = self.cleaned_data['aula'].upper()
        return aula

    class Meta:
        model = Prestamo
        fields = ['proyector', 'solicitante', 'materia', 'componentes', 'aula', 'hora_fin', 'incidencia', 'cerrado']
        labels = {
            'aula': 'Aula en donde se utilizará'
        }

class RegistroSolicitante_Form(forms.ModelForm):
    required_css_class = 'required'

    def clean_matricula(self):
        matricula = self.cleaned_data.get('matricula').upper()
        r = Solicitante.objects.filter(matricula=matricula)
        if r.count():
            raise ValidationError("Matricula ya existente")
        return matricula
        
    def clean_carrera(self):
        carrera = self.cleaned_data.get('carrera').upper()
        return carrera
        
    class Meta:
        model = Solicitante
        fields = ['matricula', 'nombre', 'ap_pat', 'ap_mat', 'carrera']
        labels = {
            'matricula': 'No. Control',
            'ap_pat': 'Apellido Paterno',
            'ap_mat': 'Apellido Materno'
        }

class RegistroMateria_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        id_materia = self.cleaned_data['id_materia'].upper()
        
    
    class Meta:
        model = Materia
        fields = ['id_materia', 'nombre']


        
class RegistroProyector_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        id_proyector = self.cleaned_data.get('id_proyector')
        r = Proyector.objects.filter(id_proyector=id_proyector)
        if r.count():
            raise ValidationError("Proyector ya existente")
        
    class Meta:    
        model = Proyector
        fields = ['id_proyector', 'descripcion', 'disponible']

class RegistroComponente_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean(self):
        id_componente = self.cleaned_data.get('id_componente')
        r = Componente.objects.filter(id_componente=id_componente)
        if r.count():
            raise ValidationError("Componente ya existente")
        
    class Meta:
        model = Componente
        fields = ['id_componente', 'nombre_componente', 'tipo_componente', 'descripcion', 'proyector']

class CheckSolicitante_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean_solicitante(self):
        solicitante = self.cleaned_data.get('solicitante')
        try:
            Solicitante.objects.get(matricula=solicitante)
        except Solicitante.DoesNotExist:
            msg = forms.ValidationError(mark_safe('Matricula no existente en el sistema. <strong>Verifique que lo haya ingresado correctamente</strong> o <a href="/prestaproyector/registrar_solicitante/">Registrese aquí</a>'))
            self.add_error('solicitante', msg)
            raise msg
        return solicitante

    class Meta:
        model = Solicitante
        fields = ['matricula']

prestaproyector/views.py
import datetime
import csv
from datetime import date, timedelta
from django.db.models import Count
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from .models import Prestamo, Proyector, Solicitante, Componente
from .forms import SolicitudProyector_Form, RegistroMateria_Form, RegistroSolicitante_Form, RegistroProyector_Form, RegistroComponente_Form
from django.contrib.auth import login, logout
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url="/prestaproyector/accounts/login/")
def dashboard(request):
    today = timezone.now()

    vigentes = Prestamo.objects.all().filter(hora_fin__gt = datetime.datetime.now(), cerrado=False)

    expirados = Prestamo.objects.filter(hora_fin__lt = datetime.datetime.now(), cerrado = False)
    prestamos = Prestamo.objects.all().order_by('-fecha_hora')
    cerrados = Prestamo.objects.all().filter(cerrado = True)
    incidencias = Prestamo.objects.all().filter(incidencia = True)
    #bloqueados = Solicitante.objects.all().filter()

    return render(request, 'dashboard.html', {'vigentes': vigentes, 'expirados':expirados ,'prestamos':prestamos, 'cerrados':cerrados, 'today':today, 'incidencias': incidencias})

def lista_prestamos(request):
    today = timezone.now()

    vigentes = Prestamo.objects.all().filter(hora_fin__gt = datetime.datetime.now(), cerrado=False)

    expirados = Prestamo.objects.filter(hora_fin__lt = datetime.datetime.now(), cerrado = False)
    prestamos = Prestamo.objects.all().order_by('-fecha_hora')
    cerrados = Prestamo.objects.all().filter(cerrado = True)
    incidencias = Prestamo.objects.all().filter(incidencia = True)
    #bloqueados = Solicitante.objects.all().filter()

    return render(request, 'lista_solicitantes.html', {'vigentes': vigentes, 'expirados':expirados ,'prestamos':prestamos, 'cerrados':cerrados, 'today':today, 'incidencias': incidencias})

@login_required(login_url="/prestaproyector/accounts/login/")
def status_proyectores(request):
    todos = Proyector.objects.all()
    todos_c = Componente.objects.all()
    no_disponibles = Proyector.objects.all().filter( disponible = False )
    no_disponibles_c = Componente.objects.all().filter( disponible = False )
    disponibles = Proyector.objects.all().filter(disponible = True)
    disponibles_c = Componente.objects.all().filter( disponible = False )
    return render(request, 'proyectores.html', {'todos':todos, 'todos_c':todos_c, 'no_disponibles':no_disponibles, 'no_disponibles_c':no_disponibles_c, 'disponibles':disponibles, 'disponibles_c':disponibles_c})

@login_required(login_url="/prestaproyector/accounts/login/")
def registrar_proyector(request):
    if request.method == 'POST':
        form = RegistroProyector_Form(request.POST)

        if form.is_valid():
            messages.success(request, 'Proyector Registrado Correctamente')
            instance = form.save(commit=False)
            instance.save()
            return redirect('proyectores')
        else:
            messages.error(request, 'Error al Registrar Proyector')
            
    else:
        form = RegistroProyector_Form()

    return render(request, 'add_proyector.html', {'form': form})

@login_required(login_url="/prestaproyector/accounts/login/")
def registrar_componente(request):
    if request.method == 'POST':
        form = RegistroComponente_Form(request.POST)

        if form.is_valid():
            messages.success(request, 'Componente Registrado Correctamente')
            instance = form.save(commit=False)
            instance.save()
            return redirect('proyectores') #Cambiar A componentes
        else:
            messages.error(request, 'Error al registrar Componente')
    else:
        form = RegistroComponente_Form()
    
    return render(request, 'add_componente.html', {'form':form})


def registrar_solicitante(request):
    if request.method == 'POST':
        form = RegistroSolicitante_Form(request.POST)

        if form.is_valid():
            messages.success(request, 'Solicitante Registrado Correctamente')
            instance = form.save(commit=False)
            instance.save()
            return redirect('solicitantes')
        else:
            messages.error(request, 'Error al Registrar')
            
    else:
        form=RegistroSolicitante_Form()

    return render(request, 'add_solicitante.html', {'form': form})

    

def solicitud(request):
    today = timezone.now()
    componentes = Componente.objects.all()
    #disponibles = Proyector.objects.all().filter(disponible = True)
    #no_disponibles = Proyector.objects.all().filter(disponible = False)
    abiertos = Prestamo.objects.all().filter(cerrado = False)
    incidentes = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=0, incidencia=True).values('solicitante')
    incidentes_count = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=0, incidencia=True).values('solicitante_count')
    sol_incidentes = Solicitante.objects.filter(matricula__in=incidentes)

    #checar si el solicitante ya tiene su tercera incidencia





    if request.method =='POST':
        solicitante_matricula = request.POST.get('solicitante')
    #else:
    #    solicitante_matricula = request.GET.get('solicitante')

    #checar si el solicitante ya tiene su tercera incidencia   
  
#    if request.method == 'POST':
#        try:
#            solicitante = Solicitante.objects.get(matricula=solicitante_matricula)
#        except Solicitante.DoesNotExist:
#            messages.error(request, 'No. de Control'+ str(solicitante_matricula) + ' no existente en el sistema. Consulte a asistente para registrar al solicitante.')
#            return redirect('solicitud')
#        if solicitante.bloqueado == True:
#            messages.error(request, 'Solicitud Denegada. Solicitante Bloqueado.')
#            return redirect('solicitud')
#        else:
#                return redirect('sol_proyector')


    return render(request, 'home.html', { 'abiertos':abiertos, 'componentes':componentes,  'today': today})

def prefill_solicitud(request):

    #filtrar componentes de proyector

        
    componentes = Componente.objects.filter(disponible = True)
    a_bloquear = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=2, incidencia=True).values('solicitante')
    sol_a_bloquear = Solicitante.objects.filter(matricula__in=a_bloquear)



    if request.method == 'POST':
        try:
            solicitante = Solicitante.objects.get(matricula=request.POST.get('solicitante'))
            if solicitante.bloqueado == True:
                messages.error(request, 'Solicitud Denegada. Solicitante Bloqueado.')
                return redirect('solicitud')
        except Solicitante.DoesNotExist:
            messages.error(request, mark_safe('No. de Control '+str(request.POST.get('solicitante')) + ' no existente en el sistema. <strong>Verifique que lo haya ingresado correctamente</strong> o <a href="/prestaproyector/registrar_solicitante/">Registrese aquí</a>'))
            return redirect('solicitud')

        


    disponibles = Proyector.objects.all().filter(disponible = True)
    no_disponibles = Proyector.objects.all().filter(disponible = False)
    abiertos = Prestamo.objects.all().filter(cerrado = False)
    incidentes = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=0, incidencia=True).values('solicitante')
    incidentes_count = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=0, incidencia=True).values('solicitante_count')
    sol_incidentes = Solicitante.objects.filter(matricula__in=incidentes)



    if request.method =='POST':
        solicitante_matricula = request.POST.get('solicitante')

    solicitante = Solicitante.objects.get(matricula=solicitante_matricula)
    
    try:
        if sol_a_bloquear.filter(matricula=solicitante.matricula).exists() and solicitante.bloqueado == False:
                solicitante.bloqueado = True
                solicitante.save()
                messages.error(request,'Solicitud Denegada. Solicitante ha sido Bloqueado.')
                return redirect('solicitud')
        elif abiertos.filter(solicitante=solicitante.matricula).exists():
            messages.error(request,'Solicitud Denegada. Solicitante no ha hecho devolución.')
            return redirect('solicitud')
        
        sol_incidentes.get(matricula=solicitante.matricula)
        incidentes_count = Prestamo.objects.values('solicitante').annotate(solicitante_count=Count('solicitante')).filter(solicitante_count__gt=0,solicitante=solicitante.matricula, incidencia=True).values('solicitante_count')
        messages.warning(request, 'Solicitante tiene ' + str(incidentes_count.count()) + " incidencia(s)")
    except Solicitante.DoesNotExist:
        pass




    materias = solicitante.materias.all()
    form = SolicitudProyector_Form()

    return render(request, 'sol_proyector.html', { 'form': form, 'disponibles':disponibles, 'no_disponibles': no_disponibles, 'abiertos':abiertos, 'materias':materias, 'solicitante':solicitante, 'componentes': componentes })

def solicitud_proyector(request):
    disponibles = Proyector.objects.all().filter(disponible = True)
    no_disponibles = Proyector.objects.all().filter(disponible = False)
    abiertos = Prestamo.objects.all().filter(cerrado = False)

prestaproyector/templates/add_componente.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Proyectores
{% endblock %}


{% block styles %}

{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}



{% block content %}

{% block messages %}
  {% include 'messages.html' %}
{% endblock %}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    <h1 class="mb-3"> Registrar Componente </h1>
  </div>

<form action="{% url 'add_componente' %}" method="post">
{% csrf_token %}
{{ form|bootstrap }}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    <button class="btn btn-warning">Registrar Componente</button>
    
    <a class="btn btn-secondary" href="{% url 'proyectores' %}" role="button">Cancelar</a>
  
  </div>



</form>

{% endblock %}

{% block scripts %}

{% endblock %}

prestaproyector/templates/add_proyector.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Registrar Proyector
{% endblock %}

{% block styles %}

{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}



{% block content %}


  {% include 'messages.html' %}


<div class="container mb-3 d-flex justify-content-between align-items-center">
    <h1 class="mb-3"> Registrar Proyector </h1>
  </div>

<form action="{% url 'add_proyector' %}" method="post">
{% csrf_token %}
{{ form|bootstrap }}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    <button class="btn btn-warning">Registrar</button>
    
    <a class="btn btn-secondary" href="{% url 'proyectores' %}" role="button">Cancelar</a>
  
  </div>



</form>

{% endblock %}

{% block scripts %}

{% endblock %}

prestaproyector/templates/add_solicitante.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Registrar Solicitante
{% endblock %}

{% block styles %}

{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}



{% block content %}

{% block messages %}
  {% include 'messages.html' %}
{% endblock %}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    <h1 class="mb-3"> Registrar Solicitante </h1>
  </div>

<form action="{% url 'add_solicitante' %}" method="post">
{% csrf_token %}
{{ form|bootstrap }}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    
    
    <a class="btn btn-secondary" href="{% url 'solicitantes' %}" role="button">Cancelar</a>
    <button type="submit" class="btn btn-warning">Registrar</button>
  
  </div>



</form>

{% endblock %}

{% block scripts %}

{% endblock %}

prestaproyector/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block subtitle %} {% endblock %} - {{ project_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">--->
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/preloader.css' %}">

    <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
    <style>
        #content-body{
          padding-top: 40px;
        }
        #header-global{
          text-decoration: none;
        }
    </style>
    {% block styles %}
  
    {% endblock %}
</head>
<body>

        <header class="topbar bg-success">
                <div class="container ">
                  <div class="flex-row d-flex justify-content-between align-items-center">
                    <div class="">

                    </div>
                    
                    <div class="">
                            <a class="text-light" id="header-global" href="#"><h1>Solicitud Proyector</h1></a>
                    </div>
                    <div class="" id="admin-btn-container" >
                        <a href="{% url 'dashboard' %}" class="text-right align-self-end" id="admin-btn"><i class="fas fa-cog"></i></a>
                    </div>
          
                  </div>
                </div>
            </header>

            {% block nav %}

            {% endblock %}
      
          <!-- Page Content -->

          <div class="container" id="content-body">
            
            {% block content %}

            {% endblock %}
          </div>

          <script src="https://code.jquery.com/jquery-3.4.0.js"
              integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
              crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
          <script src="{% static '/plugins/fontawesome/js/all.min.js' %}"></script>
          <script src="{% static '/plugins/moment/min/moment-with-locales.min.js' %}"></script>
          <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
          
          <!---script src="{% static '/js/scripts.js' %}"></script>-->
    <!--<script src="{% static '/bootstrap/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/bootstrap/popper.min.js' %}"></script>-->

    {% block scripts %}

    {% endblock %}
</body>
</html>

prestaproyector/templates/dash_navbar.html
<nav class="navbar navbar-expand navbar-light bg-light">
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'lista_prestamos' %}">Lista de Prestamos </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'proyectores' %}">Proyectores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'solicitantes' %}">Solicitantes</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="export_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Exportar datos
                </a>
                <div class="dropdown-menu" aria-labelledby="export_dropdown">
                  
                  <a class="dropdown-item" href="{% url 'exportar_csv_prestamos' %}">Exportar CSVs de Prestamos</a>
                  <a class="dropdown-item" href="{% url 'exportar_csv_solicitantes' %}">Exportar CSVs de Solicitantes</a>
                </div>
              </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <div class="dropdown">
                      <div class="dropdown-menu">
                          <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                      </div>
                    </div>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

prestaproyector/templates/dashboard.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Dashboard
{% endblock %}

{% block styles %}

{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}


{% block content %}


  {% include 'messages.html' %}



<div class="container mb-3 d-flex justify-content-between align-items-center">

        <h1 class="mb-4"> Dashboard </h1>
        <div class="ul">
        </div>
      
      </div>

<canvas id="myChart" hidden="true" width="400" height="400"></canvas>



{% endblock %}

{% block scripts %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" type="text/javascript"></script>
<script>
//var ctx = document.getElementById("myChart");
/*var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});*/
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>





{% endblock %}

prestaproyector/templates/messages.html
{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <ul>
      

        {% for error in form.non_field_errors %}

        <li>{{ error|escape }}</li>

        {% endfor %}
        {% for error,message in form.errors.items %}
        <li>Error en campo: {{ error|escape }} {{ message|escape }}</li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

{% if messages %}


      {% for message in messages %}
      {% if message.tags == 'warning' %}
      <div class="alert alert-warning alert-dismissible fade show align-self-center" role="alert">
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show align-self-center" role="alert">
        {% elif message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show align-self-center" role="alert">
          {% else %}
          <div class="alert alert-primary alert-dismissible fade show align-self-center" role="alert">
            {% endif %}
            <ul>
              <li>{{ message }}</li>
            </ul>
      
      
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          
        </div>
        {% endfor %}
{% endif %}

prestaproyector/templates/preloader.html
<div id="overlay">
        <div class="spinner"></div> 
</div>